// Code generated by MockGen. DO NOT EDIT.
// Source: backend/services/colorCategory.go

// Package mock_services is a generated GoMock package.
package mock_services

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockColorCategoryService is a mock of ColorCategoryService interface
type MockColorCategoryService struct {
	ctrl     *gomock.Controller
	recorder *MockColorCategoryServiceMockRecorder
}

// MockColorCategoryServiceMockRecorder is the mock recorder for MockColorCategoryService
type MockColorCategoryServiceMockRecorder struct {
	mock *MockColorCategoryService
}

// NewMockColorCategoryService creates a new mock instance
func NewMockColorCategoryService(ctrl *gomock.Controller) *MockColorCategoryService {
	mock := &MockColorCategoryService{ctrl: ctrl}
	mock.recorder = &MockColorCategoryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockColorCategoryService) EXPECT() *MockColorCategoryServiceMockRecorder {
	return m.recorder
}

// GetAll mocks base method
func (m *MockColorCategoryService) GetAll() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetAll indicates an expected call of GetAll
func (mr *MockColorCategoryServiceMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockColorCategoryService)(nil).GetAll))
}
